# Generated by Django 3.2 on 2023-05-29 21:42

from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodecUrls',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=350)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, django_utils.choices.Choice(1, 'Exitoso')), (2, django_utils.choices.Choice(2, 'Pendiente')), (3, django_utils.choices.Choice(3, 'Error'))], default=2)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideosUploaded',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_up/portada')),
                ('title', models.CharField(default='test', max_length=250)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.categorias')),
                ('codecurl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.codecurls')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
