# Generated by Django 4.2.30 on 2026-08-29 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_video_to_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecurls',
            name='progress',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
